#my first project in celer!
title: All Women (Bug Limit)
version: 1.4.0
route:
  use: ./main.yaml
config:
- use: Pistonight/celer-presets/botw/mini.yaml
- plugins:
  - use: link
  - use: variables
- tags:
    important:
      background: darkred
      bold: true
    women: # for counter
      background: black
      color: deeppink
    w: #for route
      color: deeppink
    wb:
      color: deeppink
      background: black
    money:
      background: black
      color: lawngreen
      bold: true
    mon:
      color: lawngreen
    val:
      background: black
      color: lawngreen
      bold: true
- icons:
    shr: https://icons.pistonite.org/icon/shrine.shrine.none.69a2d5.c1fefe.69a2d5.c1fefe.69a2d5.c1fefe.png
    incsh: https://icons.pistonite.org/icon/shrine.shrine.none.69a2d5.c1fefe.8c5e28.ffffb5.8c5e28.ffffb5.png
    tower: https://icons.pistonite.org/icon/location.tower.none.69a2d5.c1fefe.69a2d5.c1fefe.69a2d5.c1fefe.png
    statue: https://icons.pistonite.org/icon/location.lightroot.none.333333.eeeeee.333333.eeeeee.69a2d5.c1fefe.png
    hyli-w: https://icons.pistonite.org/icon/character.zelda.none.000000.000000.8c5e28.ffffb5.8c5e28.ffffb5.png
    child: https://icons.pistonite.org/icon/character.terrako.none.000000.000000.8c5e28.ffffb5.8c5e28.ffffb5.png
    zora-b: https://icons.pistonite.org/icon/character.mipha.none.000000.000000.69a2d5.c1fefe.69a2d5.c1fefe.png
    zora-p: https://icons.pistonite.org/icon/character.mipha.none.000000.000000.613b75.b96cf5.613b75.b96cf5.png
    zora-r: https://icons.pistonite.org/icon/character.mipha.none.000000.000000.f24c99.ffc0fa.f24c99.ffc0fa.png
    zora-k: https://icons.pistonite.org/icon/character.mipha.none.000000.000000.333333.eeeeee.333333.eeeeee.png
    zora-w: https://icons.pistonite.org/icon/character.mipha.none.000000.000000.aaaaaa.ffffff.aaaaaa.ffffff.png
    rito-r: https://icons.pistonite.org/icon/character.teba.none.000000.000000.f24c99.ffc0fa.f24c99.ffc0fa.png
    rito-p: https://icons.pistonite.org/icon/character.teba.none.000000.000000.d57b69.fec1d3.d57b69.fec1d3.png
    rito-b: https://icons.pistonite.org/icon/character.teba.none.000000.000000.2a767d.59ffff.2a767d.59ffff.png
    geru-w: https://icons.pistonite.org/icon/character.urbosa.none.000000.000000.8c5e28.ffffb5.8c5e28.ffffb5.png
    male: https://icons.pistonite.org/icon/character.link.none.000000.000000.8c5e28.ffffb5.8c5e28.ffffb5.png
    impa: https://icons.pistonite.org/icon/character.impa.none.2a767d.59ffff.8c5e28.ffffb5.8c5e28.ffffb5.png
    riju: https://icons.pistonite.org/icon/character.riju.none.2a767d.59ffff.8c5e28.ffffb5.8c5e28.ffffb5.png
    king: https://icons.pistonite.org/icon/character.king.none.2a767d.59ffff.8c5e28.ffffb5.8c5e28.ffffb5.png
    gfairy: https://icons.pistonite.org/icon/character.great_fairy.none.2a767d.59ffff.8c5e28.ffffb5.8c5e28.ffffb5.png
    horse: https://icons.pistonite.org/icon/misc.horse.none.613b75.b96cf5.8c5e28.ffffb5.8c5e28.ffffb5.png
    seal: https://icons.pistonite.org/icon/misc.shield.none.cfa240.ffd700.333333.eeeeee.333333.eeeeee.png
    chest: https://icons.pistonite.org/icon/shrine.blessing.none.000000.000000.8c5e28.fdfdfd.8c5e28.fdfdfd.png
    item: https://icons.pistonite.org/icon/misc.apple.none.8c5e28.ffffb5.633830.f0673a.633830.f0673a.png
    weapon: https://icons.pistonite.org/icon/shrine.sword.none.cfa240.000000.333333.eeeeee.8c5e28.ffffb5.png
    pot: https://icons.pistonite.org/icon/misc.pot.none.633830.f0673a.333333.eeeeee.8c5e28.ffffb5.png
    misc: https://icons.pistonite.org/icon/misc.double_square.none.69a2d5.c1fefe.69a2d5.c1fefe.69a2d5.c1fefe.png
    lum: https://icons.pistonite.org/icon/misc.square.none.000000.000000.2a767d.59ffff.2a767d.59ffff.png
    rar: https://icons.pistonite.org/icon/misc.square.none.000000.000000.cfa240.ffd700.cfa240.ffd700.png
    monster: https://icons.pistonite.org/icon/misc.monster.none.000000.000000.633830.f0673a.633830.f0673a.png